-- PostgreSQL schema for the Adaptive Learning System
-- Run this script against the PostgreSQL database created on Render.

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type WHERE typname = 'user_role'
    ) THEN
        CREATE TYPE user_role AS ENUM ('student', 'admin');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role user_role DEFAULT 'student',
    current_class INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
    question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer CHAR(1) NOT NULL,
    topic VARCHAR(100) DEFAULT 'General',
    class_level INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS results (
    result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    score DECIMAL(5,2),
    total_questions INTEGER,
    level_assigned VARCHAR(50),
    taken_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_results_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback (
    feedback_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id INTEGER,
    message TEXT,
    CONSTRAINT fk_feedback_result
        FOREIGN KEY (result_id)
        REFERENCES results(result_id)
        ON DELETE CASCADE
);

-- Sample questions
INSERT INTO questions
    (question_text, option_a, option_b, option_c, option_d, correct_answer, topic, class_level)
VALUES
    ('What does AI stand for?', 'Artificial Intelligence', 'Automated Input', 'Advanced Internet', 'Applied Information', 'A', 'Introduction to AI', 1),
    ('Which of the following is a type of Machine Learning?', 'Supervised Learning', 'Manual Learning', 'Forced Learning', 'Static Learning', 'A', 'Machine Learning', 1),
    ('What is the full meaning of NLP?', 'Natural Language Processing', 'Network Learning Protocol', 'New Logic Programming', 'Neural Link Process', 'A', 'NLP', 1),
    ('In rule-based systems, decisions are made using?', 'Predefined rules', 'Random guesses', 'Human emotion', 'Internet search', 'A', 'Rule-Based AI', 1),
    ('What score range is classified as Intermediate in this system?', '40% - 69%', '70% and above', 'Below 40%', '90% and above', 'A', 'Adaptive Learning', 1),
    ('Which language is commonly used for backend web development with Flask?', 'Python', 'HTML', 'CSS', 'Java', 'A', 'Web Development', 1),
    ('What does HTML stand for?', 'HyperText Markup Language', 'High Tech Modern Language', 'Hyperlink Text Management', 'Home Tool Markup Language', 'A', 'Web Development', 1),
    ('Instant feedback helps students to?', 'Correct mistakes quickly', 'Waste time', 'Skip learning', 'Avoid studying', 'A', 'Feedback Systems', 1),
    ('Adaptive learning means the system can?', 'Change content based on performance', 'Give the same content to everyone', 'Only work offline', 'Replace teachers completely', 'A', 'Adaptive Learning', 1),
    ('MySQL is a type of?', 'Database', 'Programming language', 'Web browser', 'Operating system', 'A', 'Database', 1)
ON CONFLICT DO NOTHING;
